project:
    root:       "./../"
    storage:    "./results"
    rules:      "./rules"
reports:
    -
        name: "diff"
        class: "DiffPerRule"
        target: "php://stdout"
        config:
            template: "diff_per_rule_bootstrap"
            source_url: "https://github.com/ILIAS-eLearning/ILIAS/blob/{COMMIT}/{FILE}#L{LINE}"
analysis:
    ignore:
        - ".*\\.swp"
        - ".git"
        - "composer"
        - ".*/lib"
        - ".*/test"
        - "dicto"
        - "libs"
        - "Modules/Chatroom/chat"
        - "Services/ActiveRecord/Fields/Converter/templates"
        - "Services/Mail/phpmailer"
        - "Services/PDFGeneration/classes/tcpdf"
        - "Services/Object/test/testmodule[.]xml"
        - ".*/vendor"
        - ".*[.]git.*"
        - "setup/sql"
        - ".*/HFile_.*"
        - ".*lang"
        - ".*[.]dtd"
        - ".*[.]exe"
        - ".*[.]eot"
        - ".*[.]gif"
        - ".*[.]graffle"
        - ".*[.]ico"
        - ".*[.]jar"
        - ".*[.]java"
        - ".*[.]jpeg"
        - ".*[.]jpg"
        - ".*[.]js"
        - ".*[.]mp3"
        - ".*[.]mp4"
        - ".*[.]ogg"
        - ".*[.]png"
        - ".*[.]psd"
        - ".*[.]rdf"
        - ".*[.]swf"
        - ".*[.]ttf"
        - ".*[.]woff"
        - ".*[.]woff2"
        - ".*[.]xap"
        - ".*[.]xls"
        - ".*[.]xml"
        - ".*[.]xpi"
        - ".*[.]xsd"
        - ".*[.]xsl"
        - ".*[.]zip"
        - ".*[.]pack"
        - ".*[.]pdf"