name: checks
on: [pull_request, push]
permissions:
  contents: read
  pull-requests: read
jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.2]
        nodejs: [ 20.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl, imagick
          tools: composer:v2
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Install Composer packages
        run: composer install --no-interaction --no-progress

      - name: Install Node.js packages
        run: cp public/package.json .; cp public/package-lock.json .; npm clean-install

      - name: PHP Unit Test
        run: scripts/PHPUnit/run_tests.sh
        env:
          GHRUN: "yes"

      - name: JS Unit Test
        run: npm test
        env:
          GHRUN: "yes"

      - name: PHP CS Fixer
        run: scripts/PHP-CS-Fixer/run_check.sh
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.number }}
          GH_SHA: ${{ github.sha }}

      - name: Language Sort Check
        run: scripts/sort_langfile_entries.sh check
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.number }}
          GH_SHA: ${{ github.sha }}

      - name: Special Char Checker
        run: scripts/Special-Char-Checker/special-char-checker.sh
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.number }}
          GH_SHA: ${{ github.sha }}

      - name: Copyright Check
        run: scripts/Copyright-Checker/copyright-checker.sh
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.number }}
          GH_SHA: ${{ github.sha }}
