name: checks
on: [pull_request, push]
jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0, 8.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer update && composer install --no-interaction --no-progress

      - name: PHP Unit Test 
        run: CI/PHPUnit/run_tests.sh
        env:
          GHRUN: "yes"

      - name: PHP CS Fixer
        run: CI/PHP-CS-Fixer/run_check.sh
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.number }}
          GH_SHA: ${{ github.sha }}

      - name: Language Sort Check
        run: CI/sort_langfile_entries.sh check
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.number }}
          GH_SHA: ${{ github.sha }}

      - name: Special Char Checker
        run: CI/Special-Char-Checker/special-char-checker.sh
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.number }}
          GH_SHA: ${{ github.sha }}

      - name: Copyright Check
        run: CI/Copyright-Checker/copyright-checker.sh
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.number }}
          GH_SHA: ${{ github.sha }}